name: Build and Verify

on:
  workflow_call:
    inputs:
      ref:
        type: string
        required: false
      node_version:
        type: number
        required: false
        default: 18
      sequential:
        type: boolean
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node_version }}

      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          # Simulate dependency installation
          sleep 5

      - name: Build application
        run: |
          echo "Building application..."
          mkdir -p dist
          echo "// Built application content" > dist/app.js
          echo "Build completed successfully"
          # Simulate build time
          sleep 10

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: dist/
          retention-days: 1

  verify-sequential:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ success() && inputs.sequential == true }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node_version }}

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: dist/

      - name: Run tests
        run: |
          echo "Running tests..."
          echo "Testing built application from dist/app.js"
          # Simulate test execution
          sleep 8

      - name: Run linting
        run: |
          echo "Running linting checks..."
          # Simulate linting
          sleep 3

      - name: Security scan
        run: |
          echo "Running security scans..."
          # Simulate security scanning
          sleep 5

      - name: Create verification report
        run: |
          echo "Creating verification report..."
          mkdir -p reports
          echo "All verification checks passed" > reports/verification-report.txt
          echo "Test results: PASSED" >> reports/verification-report.txt
          echo "Linting: PASSED" >> reports/verification-report.txt
          echo "Security: PASSED" >> reports/verification-report.txt

      - name: Upload verification artifacts
        uses: actions/upload-artifact@v4
        with:
          name: verification-artifacts
          path: reports/
          retention-days: 1

  verify-parallel:
    runs-on: ubuntu-latest
    if: ${{ success() && inputs.sequential == false }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node_version }}

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: dist/

      - name: Run tests
        run: |
          echo "Running tests..."
          echo "Testing built application from dist/app.js"
          # Simulate test execution
          sleep 8

      - name: Run linting
        run: |
          echo "Running linting checks..."
          # Simulate linting
          sleep 3

      - name: Security scan
        run: |
          echo "Running security scans..."
          # Simulate security scanning
          sleep 5

      - name: Create verification report
        run: |
          echo "Creating verification report..."
          mkdir -p reports
          echo "All verification checks passed" > reports/verification-report.txt
          echo "Test results: PASSED" >> reports/verification-report.txt
          echo "Linting: PASSED" >> reports/verification-report.txt
          echo "Security: PASSED" >> reports/verification-report.txt

      - name: Upload verification artifacts
        uses: actions/upload-artifact@v4
        with:
          name: verification-artifacts
          path: reports/
          retention-days: 1

  aftercare:
    runs-on: ubuntu-latest
    needs: [build, verify-sequential, verify-parallel]
    env:
      RUN_TYPE: ${{ inputs.sequential == true && 'sequential' || 'parallel' }}
    steps:
      - name: Finish up
        run: |
          echo "Finished a ${{ env.RUN_TYPE }} Build and Verify workflow"
