name: Build and Verify

on:
  workflow_call:
    inputs:
      ref:
        type: string
        required: true
      node_version:
        type: number
        required: false
        default: 18
      run-type:
        type: string
        required: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node_version }}

      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          # Simulate dependency installation
          sleep 5
          echo "Successfully installed dependencies"

      - name: Build application
        run: |
          echo "Building application..."
          mkdir -p dist
          echo "// Built application content" > dist/app.js
          echo "Build completed successfully"
          # Simulate build time
          sleep 10
          echo "Successfully built application"

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-${{ inputs.run-type }}
          path: dist/
          retention-days: 1

  verify-sequential:
    name: "Verify for a ${{ inputs.run-type }} run"
    needs:
      - build
    if: ${{ success() && inputs.run-type == 'sequential' }}
    uses: remypar5/gh-parallel-actions/.github/workflows/verify.yaml@main
    with:
      ref: ${{ inputs.ref }}
      node_version: ${{ inputs.node_version }}
      run-type: ${{ inputs.run-type }}
      
  verify-parallel:
    name: "Verify for a ${{ inputs.run-type }} run"
    if: ${{ success() && inputs.run-type == false }}
    uses: remypar5/gh-parallel-actions/.github/workflows/verify.yaml@main
    with:
      ref: ${{ inputs.ref }}
      node_version: ${{ inputs.node_version }}
      run-type: ${{ inputs.run-type }}

  aftercare:
    runs-on: ubuntu-latest
    if: ${{ always() }}
    needs: 
      - build
      - verify-sequential
      - verify-parallel
    steps:
      - name: Finish up
        run: |
          echo "Finished a ${{ inputs.run-type }} Build and Verify workflow"
