name: Build and Verify

on:
  workflow_call:
    inputs:
      ref:
        type: string
        required: true
      node_version:
        type: number
        required: false
        default: 18
      sequential:
        type: boolean
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node_version }}

      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          # Simulate dependency installation
          sleep 5
          echo "Successfully installed dependencies"

      - name: Build application
        run: |
          echo "Building application..."
          mkdir -p dist
          echo "// Built application content" > dist/app.js
          echo "Build completed successfully"
          # Simulate build time
          sleep 10
          echo "Successfully built application"

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: dist/
          retention-days: 1

  verify-sequential:
    needs:
      - build
    if: ${{ success() && inputs.sequential == true }}
    uses: remypar5/gh-parallel-actions/.github/workflows/verify.yaml@main
    with:
      ref: ${{ inputs.ref }}
      node_version: ${{ inputs.node_version }}
      sequential: ${{ inputs.sequential }}
      
  verify-parallel:
    if: ${{ success() && inputs.sequential == false }}
    uses: remypar5/gh-parallel-actions/.github/workflows/verify.yaml@main
    with:
      ref: ${{ inputs.ref }}
      node_version: ${{ inputs.node_version }}
      sequential: ${{ inputs.sequential }}

  aftercare:
    runs-on: ubuntu-latest
    if: ${{ success() }}
    needs: 
      - build
      - verify-sequential
      - verify-parallel
    env:
      RUN_TYPE: ${{ inputs.sequential == true && 'sequential' || 'parallel' }}
    steps:
      - name: Finish up
        run: |
          echo "Finished a ${{ env.RUN_TYPE }} Build and Verify workflow"
