name: Main Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  run-sequential:
    uses: remypar5/gh-parallel-actions/.github/workflows/sequential.yaml@main

  run-parallel:
    uses: remypar5/gh-parallel-actions/.github/workflows/parallel.yaml@main

  ready:
    runs-on: ubuntu-latest
    needs:
      - run-sequential
      - run-parallel
    steps:
      - name: Closing thoughts
        run: echo "I'm done here"
