name: Verify
on:
  workflow_call:
    inputs:
      ref:
        type: string
        required: true
      node_version:
        type: number
        required: false
        default: 18
      run-type:
        type: string
        required: true

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node_version }}

      - name: Download build artifacts
        if: ${{ inputs.run-type == 'sequential' }}
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts-${{ inputs.run-type }}
          path: dist/

      - name: Run tests
        run: |
          echo "Running tests..."
          echo "Testing built application from dist/app.js"
          # Simulate test execution
          sleep 2

      - name: Run linting
        run: |
          echo "Running linting checks..."
          # Simulate linting
          sleep 2

      - name: Security scan
        run: |
          echo "Running security scans..."
          # Simulate security scanning
          sleep 2

      - name: Create verification report
        run: |
          echo "Creating verification report..."
          mkdir -p reports
          sleep 2
          echo "All verification checks passed" > reports/verification-report.txt
          sleep 2
          echo "Test results: PASSED" >> reports/verification-report.txt
          sleep 2
          echo "Linting: PASSED" >> reports/verification-report.txt
          sleep 2
          echo "Security: PASSED" >> reports/verification-report.txt

      - name: Upload verification artifacts
        uses: actions/upload-artifact@v4
        with:
          name: verification-artifacts-${{ inputs.run-type }}
          path: reports/
          retention-days: 1
